In [28]:
import pandas as pd

# Read the text file line by line
with open('results.txt', 'r') as file:
    lines = file.readlines()

# Initialize lists to store data
names = []
extensions = []
depths = []
sizes = []

# Split each line and extract values
for line in lines:
    parts = line.strip().split('\t')
    name, extension = parts[0].split('.')
    depth = int(parts[1])
    size = int(parts[2])
    
    # Append extracted values to lists
    names.append(name)
    extensions.append(extension)
    depths.append(depth)
    sizes.append(size)

# Create DataFrame
input_df = pd.DataFrame({
    'name': names,
    'extension': extensions,
    'depth': depths,
    'size': sizes
})

# Print the DataFrame
input_df

          name extension  depth  size
0     nlsp_2_0       inp      0     0
1    nlsp_2_10       inp      0     0
2    nlsp_2_11       inp      3     3
3    nlsp_2_12       inp      0     0
4    nlsp_2_13       inp      3     3
..         ...       ...    ...   ...
267  nlsp_3_96       inp      4     7
268  nlsp_3_97       inp      4    10
269  nlsp_3_98       inp      4     6
270  nlsp_3_99       inp      4     9
271   nlsp_3_9       inp      4     6

[272 rows x 4 columns]

In [29]:
import os
import pandas as pd

# Directory containing the files
directory = '../out'

# Initialize lists to store data
names = []
extensions = []
numbers = []
depths = []
sizes = []
# Iterate over files in the directory
for filename in os.listdir(directory):
    if os.path.isfile(os.path.join(directory, filename)):
        name, extension = os.path.splitext(filename)
        names.append(name)
        extensions.append(extension)

    # Read the first line of the file and extract the number
    with open(os.path.join(directory, filename), 'r') as file:
        first_line = file.readline().strip()
        n = int(first_line) if first_line.isdigit() else 0
        numbers.append(n)

        # Read first_line_number rows and extract two numbers from the first row
        depth, size = None, None
        result = pow(2, n)
        for i, line in enumerate(file):
            if i == result:
                depth, size = map(int, line.strip().split())
                break

        depths.append(depth)
        sizes.append(size)

# Create DataFrame
output_df = pd.DataFrame({
    'name': names,
    'extension': extensions,
    'n': numbers,
    'depth': depths,
    'size': sizes
})

# Print the DataFrame
output_df

          name extension  n  depth  size
0   nlsp_3_192      .out  3    2.0   3.0
1     nlsp_3_0      .out  3    0.0   0.0
2   nlsp_3_224      .out  3    2.0   3.0
3   nlsp_3_234      .out  3    2.0   3.0
4   nlsp_3_168      .out  3    2.0   3.0
5   nlsp_3_236      .out  3    2.0   3.0
6     nlsp_2_1      .out  2    1.0   1.0
7    nlsp_2_12      .out  2    0.0   0.0
8    nlsp_2_13      .out  2    3.0   3.0
9     nlsp_2_0      .out  2    0.0   0.0
10  nlsp_3_250      .out  3    2.0   2.0
11  nlsp_3_252      .out  3    2.0   2.0
12    nlsp_2_2      .out  2    2.0   2.0
13   nlsp_2_11      .out  2    3.0   3.0
14   nlsp_2_10      .out  2    0.0   0.0
15    nlsp_2_3      .out  2    1.0   1.0
16    nlsp_2_7      .out  2    3.0   4.0
17   nlsp_2_14      .out  2    2.0   2.0
18   nlsp_2_15      .out  2    1.0   1.0
19    nlsp_2_6      .out  2    3.0   5.0
20  nlsp_3_254      .out  0    NaN   NaN
21  nlsp_3_240      .out  3    0.0   0.0
22  nlsp_3_136      .out  3    2.0   3.0
23    nlsp_2_4      .out  2    2.0   2.0
24    nlsp_2_5      .out  2    1.0   1.0
25    nlsp_2_8      .out  2    2.0   3.0
26    nlsp_2_9      .out  2    3.0   5.0
27  nlsp_3_248      .out  3    2.0   3.0
28   nlsp_3_10      .out  3    2.0   2.0
29  nlsp_3_170      .out  3    0.0   0.0
30  nlsp_3_238      .out  3    2.0   2.0
31  nlsp_3_204      .out  3    0.0   0.0
32   nlsp_3_12      .out  3    2.0   2.0
33   nlsp_3_17      .out  3    1.0   1.0
34  nlsp_3_200      .out  3    2.0   3.0
35   nlsp_3_15      .out  3    1.0   1.0
36  nlsp_3_160      .out  3    2.0   3.0
37   nlsp_3_14      .out  3    2.0   2.0

In [30]:
# Merge the two dataframes on 'name', 'depth', and 'size'
merged_df = pd.merge(input_df, output_df, on=['name', 'depth', 'size'], how='inner')

# Count the number of rows with the same 'name', 'depth', and 'size'
count_df = merged_df.groupby(['name', 'depth', 'size']).size().reset_index(name='count')

count_df

          name  depth  size  count
0     nlsp_2_0      0     0      1
1     nlsp_2_1      1     1      1
2    nlsp_2_10      0     0      1
3    nlsp_2_11      3     3      1
4    nlsp_2_12      0     0      1
5    nlsp_2_13      3     3      1
6    nlsp_2_14      2     2      1
7    nlsp_2_15      1     1      1
8     nlsp_2_2      2     2      1
9     nlsp_2_3      1     1      1
10    nlsp_2_4      2     2      1
11    nlsp_2_5      1     1      1
12    nlsp_2_6      3     5      1
13    nlsp_2_7      3     4      1
14    nlsp_2_8      2     3      1
15    nlsp_2_9      3     5      1
16    nlsp_3_0      0     0      1
17   nlsp_3_10      2     2      1
18   nlsp_3_12      2     2      1
19  nlsp_3_136      2     3      1
20   nlsp_3_14      2     2      1
21   nlsp_3_15      1     1      1
22  nlsp_3_160      2     3      1
23  nlsp_3_168      2     3      1
24   nlsp_3_17      1     1      1
25  nlsp_3_170      0     0      1
26  nlsp_3_192      2     3      1
27  nlsp_3_200      2     3      1
28  nlsp_3_204      0     0      1
29  nlsp_3_224      2     3      1
30  nlsp_3_234      2     3      1
31  nlsp_3_236      2     3      1
32  nlsp_3_238      2     2      1
33  nlsp_3_240      0     0      1
34  nlsp_3_248      2     3      1
35  nlsp_3_250      2     2      1
36  nlsp_3_252      2     2      1